### PR TITLE
I found this format much easier to read

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by julienw** [comment]
I agree with this but we need a "debug" mode that would display as a debug format all notifications (so outside of the match). What do you think ?

**Comment by dhylands** [comment]
Well this still shows more notifications than were shown before. I didn't change the default case on the match - that's the way it was already.

The other change was to change {:?} (which is totally unreadable) to {}

**Comment by julienw** [comment]
So I gave more thoughts to this.

I think we should know totally remove any printed things from the stateful-rust library and instead propagate some events to the consumer. Then the consumer can print things if it needs to.

The Debug format is useful in that it shows everything the object has. You can pretty print it BTW, using `:#?` instead of just `:?`.

So I'd rather not accept this and instead we need to work on passing down events which we'll need for the adapter anyway.
But if you really want this, we can still land it given it's only temporary.

**Comment by dhylands** [comment]
What I found really useful about it is that its just one line per notification. By printing using {:?} we're printing several lines per notification and so much information goes by its very difficult to pick out the useful stuff (like timeouts).

So I find it useful, even if temporary.

I also like the idea of not having openwave-stateful-rust not print anything and give a mechanism to the calling app to do so. Or perhaps have a default printing function that the calling app could call.

**Comment by julienw** [comment]
> Or perhaps have a default printing function that the calling app could call.

Well, the default printing function _is_ the Display impl :)

**Pull request merged**
